// Generated by blendx from blends/. Do not edit; run `blendx generate`.
// Each table: its actions as "METHOD /path", and the tables its includes point to.
// Imports nothing, so a web app can load it.

export const tables = {
  "order_notes": {
    "actions": {
      "index": "GET /order_notes",
      "store": "POST /order_notes",
    },
    "includes": {},
  },
  "orders": {
    "actions": {
      "index": "GET /orders",
      "store": "POST /orders",
      "quote": "GET /orders/quote",
      "show": "GET /orders/:id",
      "update": "PATCH /orders/:id",
      "destroy": "DELETE /orders/:id",
      "restore": "POST /orders/:id/restore",
      "refund": "POST /orders/:id/refund",
    },
    "includes": {
      "user": "users",
    },
  },
  "users": {
    "actions": {
      "store": "POST /users",
      "show": "GET /users/:id",
      "update": "PATCH /users/:id",
    },
    "includes": {},
  },
} as const;
