// Generated by blendx from blends/. Do not edit; run `blendx generate`.

import { router, run } from "blendx";
import order_notes from "../fixtures/shop/blends/order_notes.ts";
import orders from "../fixtures/shop/blends/orders.ts";
import users from "../fixtures/shop/blends/users.ts";

export const routes = router()
  .get("/order_notes", ...run(order_notes, "index"))
  .post("/order_notes", ...run(order_notes, "store"))
  .get("/order_notes/:id", ...run(order_notes, "show"))
  .get("/orders", ...run(orders, "index"))
  .post("/orders", ...run(orders, "store"))
  .get("/orders/quote", ...run(orders, "quote"))
  .get("/orders/:id", ...run(orders, "show"))
  .patch("/orders/:id", ...run(orders, "update"))
  .delete("/orders/:id", ...run(orders, "destroy"))
  .post("/orders/:id/restore", ...run(orders, "restore"))
  .post("/orders/:id/refund", ...run(orders, "refund"))
  .post("/users", ...run(users, "store"))
  .get("/users/:id", ...run(users, "show"))
  .patch("/users/:id", ...run(users, "update"));

export const resources = [order_notes, orders, users];

export type AppType = typeof routes;
