import { describe, expect, test } from 'bun:test';
import { join } from 'node:path';
import { loadSchema } from '@blendx/dbml';
import { emitDrizzle } from '../src/emit-drizzle.ts';

const fixture = (name: string) => Bun.file(join(import.meta.dir, 'fixtures', name)).text();

/** Compares with the committed golden file. Missing goldens are written once (never on CI). */
async function expectGolden(name: string, actual: string) {
  const path = join(import.meta.dir, 'golden', name);
  if (process.env.UPDATE_GOLDEN === '1' || (!(await Bun.file(path).exists()) && !process.env.CI)) {
    await Bun.write(path, actual);
  }
  // A fresh handle: a BunFile that was checked before the write can return stale content.
  expect(actual).toBe(await Bun.file(path).text());
}

describe('emitDrizzle', () => {
  test('addition fixture', async () => {
    await expectGolden(
      'addition.schema.gen.ts',
      emitDrizzle(await loadSchema(await fixture('addition.dbml'))),
    );
  });

  test('shop fixture: enum, foreign keys, indexes, uniques, defaults, arrays', async () => {
    await expectGolden(
      'shop.schema.gen.ts',
      emitDrizzle(await loadSchema(await fixture('shop.dbml'))),
    );
  });

  test('imports only the builders it uses', async () => {
    const output = emitDrizzle(await loadSchema(await fixture('addition.dbml')));
    expect(output).toContain(
      'import { doublePrecision, integer, pgTable, timestamp } from "drizzle-orm/pg-core";',
    );
    expect(output).not.toContain('from "drizzle-orm";');
  });

  test('output is deterministic', async () => {
    const schema = await loadSchema(await fixture('shop.dbml'));
    expect(emitDrizzle(schema)).toBe(emitDrizzle(schema));
  });

  test('an empty schema still exports models', () => {
    expect(emitDrizzle({ tables: [], enums: [] })).toBe(
      '// Generated by blendx from schema.dbml. Do not edit; run `blendx generate`.\n\nexport const models = {} as const;\n',
    );
  });
});
