import { describe, expect, test } from 'bun:test';
import { join } from 'node:path';
import { loadSchema, tableConstraints } from '@blendx/dbml';
import { emitDrizzle } from '../src/emit-drizzle.ts';

const fixture = (name: string) => Bun.file(join(import.meta.dir, 'fixtures', name)).text();

/** Compares with the committed golden file. Missing goldens are written once (never on CI). */
async function expectGolden(name: string, actual: string) {
  const path = join(import.meta.dir, 'golden', name);
  if (process.env.UPDATE_GOLDEN === '1' || (!(await Bun.file(path).exists()) && !process.env.CI)) {
    await Bun.write(path, actual);
  }
  // A fresh handle: a BunFile that was checked before the write can return stale content.
  expect(actual).toBe(await Bun.file(path).text());
}

describe('emitDrizzle', () => {
  test('addition fixture', async () => {
    await expectGolden(
      'addition.schema.gen.ts',
      emitDrizzle(await loadSchema(await fixture('addition.dbml'))),
    );
  });

  test('shop fixture: enum, foreign keys, indexes, uniques, defaults, arrays', async () => {
    await expectGolden(
      'shop.schema.gen.ts',
      emitDrizzle(await loadSchema(await fixture('shop.dbml'))),
    );
  });

  test('kitchen-sink fixture: a composite primary key is a named table constraint (D33)', async () => {
    const output = emitDrizzle(await loadSchema(await fixture('kitchen-sink.dbml')));
    await expectGolden('kitchen-sink.schema.gen.ts', output);
    expect(output).toContain(
      'primaryKey({ name: "order_items_pkey", columns: [t.order_id, t.line] })',
    );
    expect(output).toContain('order_id: bigint({ mode: "number" }).notNull(),');
    expect(output).toContain('primaryKey: ["order_id", "line"],');
    expect(output).toContain('primaryKey: ["id"],');
  });

  test('imports only the builders it uses', async () => {
    const output = emitDrizzle(await loadSchema(await fixture('addition.dbml')));
    expect(output).toContain(
      'import { doublePrecision, integer, pgTable, timestamp } from "drizzle-orm/pg-core";',
    );
    expect(output).not.toContain('from "drizzle-orm";');
  });

  test('importFrom: every builder and sql from one module, no drizzle-orm imports', async () => {
    const schema = await loadSchema(
      "Table codes {\n  id int [pk]\n  code text [default: `upper('x')`]\n}\n",
    );
    const output = emitDrizzle(schema, { importFrom: 'blendx/drizzle' });
    expect(output).toContain('import { integer, pgTable, sql, text } from "blendx/drizzle";');
    expect(output).not.toContain('drizzle-orm');
  });

  test('output is deterministic', async () => {
    const schema = await loadSchema(await fixture('shop.dbml'));
    expect(emitDrizzle(schema)).toBe(emitDrizzle(schema));
  });

  test('tableConstraints lists every name Postgres can report, with its columns', async () => {
    const { tables } = await loadSchema(await fixture('shop.dbml'));
    const byName = Object.fromEntries(tables.map((t) => [t.name, t]));
    if (!byName.users || !byName.orders) throw new Error('shop fixture changed');

    expect(tableConstraints(byName.users)).toEqual([
      ['users_pkey', { kind: 'primaryKey', columns: ['id'] }],
      ['users_email_key', { kind: 'unique', columns: ['email'] }],
    ]);
    expect(tableConstraints(byName.orders)).toEqual([
      ['orders_pkey', { kind: 'primaryKey', columns: ['id'] }],
      ['orders_public_id_key', { kind: 'unique', columns: ['public_id'] }],
      [
        'orders_user_id_fkey',
        {
          kind: 'foreignKey',
          columns: ['user_id'],
          references: { table: 'users', columns: ['id'] },
        },
      ],
    ]);
  });

  test('a composite primary key is one constraint with every column (D33)', async () => {
    const { tables } = await loadSchema(await fixture('kitchen-sink.dbml'));
    const items = tables.find((t) => t.name === 'order_items');
    if (!items) throw new Error('kitchen-sink fixture changed');
    expect(tableConstraints(items)).toEqual([
      ['order_items_pkey', { kind: 'primaryKey', columns: ['order_id', 'line'] }],
      [
        'order_items_order_id_fkey',
        {
          kind: 'foreignKey',
          columns: ['order_id'],
          references: { table: 'orders', columns: ['id'] },
        },
      ],
    ]);
  });

  test('unique indexes count as constraints (a 23505 error names the index)', async () => {
    const { tables } = await loadSchema(
      'Table pairs {\n  id int [pk]\n  a int\n  b int\n  indexes {\n    (a, b) [unique]\n  }\n}\n',
    );
    const pairs = tables[0];
    if (!pairs) throw new Error('no table');
    expect(tableConstraints(pairs)).toEqual([
      ['pairs_pkey', { kind: 'primaryKey', columns: ['id'] }],
      ['pairs_a_b_key', { kind: 'unique', columns: ['a', 'b'] }],
    ]);
  });

  test('an empty schema still exports models', () => {
    expect(emitDrizzle({ tables: [], enums: [] })).toBe(
      '// Generated by blendx from schema.dbml. Do not edit; run `blendx generate`.\n\nexport const models = {} as const;\n',
    );
  });
});
