/**
 * blendx: the only package app code imports. It re-exports the authoring API from
 * @blendx/core, the Hono adapter, and zod's `z`.
 */
export const PACKAGE = 'blendx';

export {
  type App,
  type AppActionBuilder,
  type AppActionContext,
  type AppActionDefinition,
  AppActionDefinitionError,
  type AppActionHandler,
  type AppActionMethod,
  type AppActionReply,
  type AppActionResult,
  type AppSpec,
  allow,
  BlendxConfigError,
  BlendxDefinitionError,
  blend,
  type DataMigration,
  type Db,
  type DrainResult,
  dataMigration,
  defineApp,
  defineConfig,
  deny,
  drainOutbox,
  HttpProblem,
  type Model,
  type MultipartInput,
  multipart,
  type OutboxOptions,
  type OutboxWorker,
  type Policy,
  PROBLEM_CONTENT_TYPE,
  type ProblemDetails,
  type PublicRow,
  problem,
  type Register,
  type RegisteredAuth,
  type RelationColumnMap,
  type RelationKey,
  type RelationKeyColumnMap,
  RelationWriteDefinitionError,
  type ReplaceRelationOptions,
  type Reply,
  type Resource,
  type Row,
  replaceRelation,
  startOutbox,
  type Writes,
} from '@blendx/core';
export {
  type AppActionInputOf,
  type AppActionResponseOf,
  type BlendxEnv,
  createServer,
  type RunActionTuple,
  router,
  run,
  runAction,
  type ServerOptions,
} from '@blendx/hono';
export { z } from 'zod';
export {
  createDatabase,
  type Database,
  type DatabaseConfig,
  DataMigrationError,
  type MigrationResult,
} from './database.ts';
