import {
  type ColumnIR,
  type ColumnType,
  deriveConventions,
  type SchemaIR,
  type TableIR,
} from './ir.ts';

const HEADER = '// Generated by blendx from schema.dbml. Do not edit; run `blendx generate`.';

/**
 * Postgres-style constraint and index names. They are spelled out in the generated
 * schema so a database error can be traced back to its columns (P2.7, P5.7).
 */
export const constraintNames = {
  primaryKey: (table: string) => `${table}_pkey`,
  unique: (table: string, columns: string[]) => `${table}_${columns.join('_')}_key`,
  foreignKey: (table: string, columns: string[]) => `${table}_${columns.join('_')}_fkey`,
  index: (table: string, columns: string[]) => `${table}_${columns.join('_')}_idx`,
};

export type ConstraintKind = 'primaryKey' | 'unique' | 'foreignKey';

export interface ConstraintInfo {
  kind: ConstraintKind;
  columns: string[];
  references?: { table: string; columns: string[] };
}

/**
 * Every constraint name Postgres can report for a table, in a stable order. Unique
 * indexes are included: a 23505 error names the index as its constraint.
 */
export function tableConstraints(table: TableIR): [name: string, info: ConstraintInfo][] {
  const constraints: [string, ConstraintInfo][] = [];
  if (table.primaryKey.length > 0) {
    constraints.push([
      constraintNames.primaryKey(table.name),
      { kind: 'primaryKey', columns: [...table.primaryKey] },
    ]);
  }
  const singlePk = table.primaryKey.length === 1 ? table.primaryKey[0] : undefined;
  for (const column of table.columns) {
    if (column.unique && column.name !== singlePk) {
      constraints.push([
        constraintNames.unique(table.name, [column.name]),
        { kind: 'unique', columns: [column.name] },
      ]);
    }
  }
  for (const index of table.indexes) {
    if (!index.unique) continue;
    constraints.push([
      index.name ?? constraintNames.unique(table.name, index.columns),
      { kind: 'unique', columns: [...index.columns] },
    ]);
  }
  for (const fk of table.foreignKeys) {
    constraints.push([
      constraintNames.foreignKey(table.name, fk.columns),
      {
        kind: 'foreignKey',
        columns: [...fk.columns],
        references: { table: fk.references.table, columns: [...fk.references.columns] },
      },
    ]);
  }
  return constraints;
}

const str = (value: string) => JSON.stringify(value);

/** `{ a: 1, b: 2 }` for the defined entries, or an empty string when there are none. */
function options(entries: Record<string, string | number | boolean | undefined>): string {
  const parts = Object.entries(entries)
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) => `${key}: ${typeof value === 'string' ? str(value) : String(value)}`);
  return parts.length > 0 ? `{ ${parts.join(', ')} }` : '';
}

export interface EmitDrizzleOptions {
  /**
   * Import every builder and `sql` from this one module instead of drizzle-orm. The CLI
   * passes 'blendx/drizzle', so an app shares the drizzle-orm that blendx is built on.
   */
  importFrom?: string;
}

/** Emits schema.gen.ts for a validated schema IR. Output is deterministic. */
export function emitDrizzle(schema: SchemaIR, settings: EmitDrizzleOptions = {}): string {
  const pgCore = new Set<string>();
  let usesSql = false;
  const use = (name: string) => {
    pgCore.add(name);
    return name;
  };

  const builder = (type: ColumnType): string => {
    switch (type.kind) {
      case 'smallint':
      case 'integer':
      case 'real':
      case 'text':
      case 'boolean':
      case 'uuid':
      case 'json':
      case 'jsonb':
      case 'time':
        return `${use(type.kind)}()`;
      case 'bigint':
        return `${use('bigint')}({ mode: "number" })`;
      case 'double':
        return `${use('doublePrecision')}()`;
      case 'numeric':
        return `${use('numeric')}(${options({ precision: type.precision, scale: type.scale })})`;
      case 'varchar':
      case 'char':
        return `${use(type.kind)}(${options({ length: type.length })})`;
      case 'date':
        return `${use('date')}({ mode: "string" })`;
      case 'timestamp':
        return `${use('timestamp')}(${options({ mode: 'string', withTimezone: type.withTimezone || undefined })})`;
      case 'enum':
        return `${type.name}()`;
      case 'array':
        return `${builder(type.of)}.array()`;
    }
  };

  const sqlDefault = (text: string) => {
    usesSql = true;
    return `.default(sql\`${text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}\`)`;
  };

  const defaultOf = (column: ColumnIR): string => {
    const value = column.default;
    if (!value) return '';
    if (value.kind === 'expression') {
      const expression = value.sql.trim().toLowerCase();
      if (expression === 'now()' && column.type.kind === 'timestamp') return '.defaultNow()';
      if (expression === 'gen_random_uuid()' && column.type.kind === 'uuid')
        return '.defaultRandom()';
      return sqlDefault(value.sql);
    }
    if (value.value === null) return '';
    switch (column.type.kind) {
      case 'numeric':
        return `.default(${str(String(value.value))})`;
      case 'json':
      case 'jsonb':
        try {
          return `.default(${JSON.stringify(JSON.parse(String(value.value)))})`;
        } catch {
          return sqlDefault(`'${String(value.value).replace(/'/g, "''")}'`);
        }
      case 'array':
        return sqlDefault(`'${String(value.value).replace(/'/g, "''")}'`);
      default:
        return `.default(${JSON.stringify(value.value)})`;
    }
  };

  const columnLine = (table: TableIR, column: ColumnIR): string => {
    const isPk = table.primaryKey.length === 1 && table.primaryKey[0] === column.name;
    let code = builder(column.type);
    if (isPk) code += '.primaryKey()';
    if (column.increment) code += '.generatedAlwaysAsIdentity()';
    if (!column.nullable && !isPk) code += '.notNull()';
    if (column.unique && !isPk)
      code += `.unique(${str(constraintNames.unique(table.name, [column.name]))})`;
    code += defaultOf(column);
    return `    ${column.name}: ${code},`;
  };

  const extrasOf = (table: TableIR): string[] => {
    const own = (columns: string[]) => columns.map((c) => `t.${c}`).join(', ');
    const extras: string[] = [];
    // D33: a composite key is a table constraint, named as Postgres names a primary key.
    if (table.primaryKey.length > 1) {
      extras.push(
        `${use('primaryKey')}({ name: ${str(constraintNames.primaryKey(table.name))}, columns: [${own(table.primaryKey)}] })`,
      );
    }
    for (const fk of table.foreignKeys) {
      const target = fk.references.table === table.name ? 't' : fk.references.table;
      const foreignColumns = fk.references.columns.map((c) => `${target}.${c}`).join(', ');
      let code = `${use('foreignKey')}({ name: ${str(constraintNames.foreignKey(table.name, fk.columns))}, columns: [${own(fk.columns)}], foreignColumns: [${foreignColumns}] })`;
      if (fk.onDelete) code += `.onDelete(${str(fk.onDelete)})`;
      if (fk.onUpdate) code += `.onUpdate(${str(fk.onUpdate)})`;
      extras.push(code);
    }
    for (const index of table.indexes) {
      const name =
        index.name ??
        (index.unique
          ? constraintNames.unique(table.name, index.columns)
          : constraintNames.index(table.name, index.columns));
      extras.push(
        `${use(index.unique ? 'uniqueIndex' : 'index')}(${str(name)}).on(${own(index.columns)})`,
      );
    }
    return extras;
  };

  const enumLines = schema.enums.map(
    (e) =>
      `export const ${e.name} = ${use('pgEnum')}(${str(e.name)}, [${e.values.map(str).join(', ')}]);`,
  );

  const tableBlocks = schema.tables.map((table) => {
    const columns = table.columns.map((column) => columnLine(table, column)).join('\n');
    const extras = extrasOf(table);
    const extraConfig =
      extras.length > 0 ? `, (t) => [\n${extras.map((e) => `  ${e},`).join('\n')}\n]` : '';
    return `export const ${table.name} = ${use('pgTable')}(${str(table.name)}, {\n${columns.replace(/^ {2}/gm, '')}\n}${extraConfig});`;
  });

  const constraintLines = (table: TableIR): string[] => {
    const entries = tableConstraints(table).map(([name, info]) => {
      const columns = `[${info.columns.map(str).join(', ')}]`;
      const references = info.references
        ? `, references: { table: ${str(info.references.table)}, columns: [${info.references.columns.map(str).join(', ')}] }`
        : '';
      return `        ${str(name)}: { kind: ${str(info.kind)}, columns: ${columns}${references} },`;
    });
    return entries.length > 0
      ? ['      constraints: {', ...entries, '      },']
      : ['      constraints: {},'];
  };

  const modelEntries = schema.tables.map((table) => {
    const conventions = deriveConventions(table);
    const nullable = (value: string | undefined) => (value === undefined ? 'null' : str(value));
    return [
      `  ${table.name}: {`,
      `    name: ${str(table.name)},`,
      `    table: ${table.name},`,
      '    meta: {',
      `      primaryKey: [${table.primaryKey.map(str).join(', ')}],`,
      `      timestamps: { createdAt: ${nullable(conventions.timestamps.createdAt)}, updatedAt: ${nullable(conventions.timestamps.updatedAt)} },`,
      `      softDelete: ${nullable(conventions.softDelete?.column)},`,
      `      generated: [${conventions.generated.map(str).join(', ')}],`,
      ...constraintLines(table),
      '    },',
      '  },',
    ].join('\n');
  });

  const imports: string[] = [];
  if (settings.importFrom) {
    const names = [...pgCore, ...(usesSql ? ['sql'] : [])].sort();
    if (names.length > 0) {
      imports.push(`import { ${names.join(', ')} } from ${str(settings.importFrom)};`);
    }
  } else {
    if (usesSql) imports.push('import { sql } from "drizzle-orm";');
    if (pgCore.size > 0) {
      imports.push(`import { ${[...pgCore].sort().join(', ')} } from "drizzle-orm/pg-core";`);
    }
  }
  const models =
    modelEntries.length > 0
      ? `export const models = {\n${modelEntries.join('\n')}\n} as const;`
      : 'export const models = {} as const;';

  return `${[HEADER, imports.join('\n'), ...enumLines, ...tableBlocks, models].filter(Boolean).join('\n\n')}\n`;
}
