/**
 * P10.3: review/<resource>.yaml. The golden is the addition example's own review file; the
 * other tests pin the comments, the layout and determinism. The TypeScript 6 program that
 * reads calculate is built once: it loads the app's full types and takes a few seconds.
 */
import { beforeAll, describe, expect, test } from 'bun:test';
import { join } from 'node:path';
import {
  type App,
  allow,
  blend,
  defineApp,
  type Resource,
  type ResourceReview,
  reviewResource,
} from '@blendx/core';
import { parse } from 'yaml';
import { models as shop } from '../../dbml/test/golden/shop.schema.gen.ts';
import { type CalculateSource, extractCalculates } from '../src/calculates.ts';
import { emitReview } from '../src/emit-review.ts';
import { expectGolden } from './support/golden.ts';

const example = join(import.meta.dir, '..', '..', '..', 'examples', 'addition');
const blendFile = join(example, 'blends', 'addition_results.ts');

let review: ResourceReview;
let calculates: ReadonlyMap<string, CalculateSource> | undefined;
beforeAll(async () => {
  // Computed paths keep the example out of this package's tsc program.
  const resource = (await import(blendFile)).default as Resource;
  const app = (await import(join(example, 'src', 'app.ts'))).default as App;
  review = reviewResource(resource, app);
  calculates = extractCalculates([blendFile]).get(blendFile);
}, 60_000);

const additionReview = () =>
  emitReview({ review, calculates, source: 'blends/addition_results.ts' });

describe('emitReview', () => {
  test('the addition example', async () => {
    await expectGolden(join(example, 'review', 'addition_results.yaml'), additionReview());
  });

  test('the same review twice is the same text', () => {
    expect(additionReview()).toBe(additionReview());
  });

  test('stages shaped by a hook say so; calculate shows its source and writes', () => {
    const text = additionReview();
    expect(text).toContain("    calculate: the input's writable columns # from: schema, action\n");
    const store = parse(text).actions.store;
    expect(store.calculate).toEqual({
      source: '({ input }) => ({ result: input.a + input.b })',
      writes: ['result'],
    });
    expect(store.reply).toEqual({ status: 201, body: 'the record' });
  });

  test('a scoped index shows its scope, and its load says the action shaped it (D22)', () => {
    const orders = blend(shop.orders, {
      policy: allow.authenticated,
      actions: (a) => [
        a.index({ scope: ({ auth }) => ({ user_id: (auth as { id: number } | null)?.id }) }),
      ],
    });
    const scoped = reviewResource(orders, defineApp({}));
    const source = '({ auth }) => ({ user_id: auth?.id })';
    const text = emitReview({
      review: scoped,
      scopes: new Map([['index', { source, keys: ['user_id'] }]]),
      source: 'blends/orders.ts',
    });
    expect(text).toContain(
      'load: a filtered, sorted page of rows that are not soft-deleted # from: schema, action',
    );
    expect(parse(text).actions.index.scope).toEqual({ source, columns: ['user_id'] });
    const unread = emitReview({ review: scoped, source: 'blends/orders.ts' });
    expect(parse(unread).actions.index.scope).toBe(
      'not read: write scope inline in the blend file',
    );
  });

  test('hidden columns, resource hooks, and a default calculate', () => {
    const users = blend(shop.users, {
      policy: allow.when(({ auth }) => auth !== null, { description: 'signed-in users' }),
      hidden: ['password'],
      hooks: { authorize: ({ prev }) => prev },
      actions: (a) => [a.store(), a.show()],
    });
    const text = emitReview({
      review: reviewResource(users, defineApp({})),
      source: 'blends/users.ts',
    });
    expect(text).toStartWith('# Generated by `blendx review`.');
    expect(text).toContain('\nhidden: [password]\n');
    expect(text).toContain('    authorize: signed-in users # from: schema, resource\n');
    const parsed = parse(text);
    expect(parsed.format).toBe(1);
    expect(parsed.record.password).toBeUndefined();
    expect(parsed.actions.store.calculate).toEqual({
      writes: ['display_name', 'email', 'is_active', 'password'],
    });
    expect(parsed.actions.show.calculate).toBeUndefined();
  });
});
