/**
 * P10.3: review/<resource>.yaml. The golden is the addition example's own review file; the
 * other tests pin the comments, the layout and determinism. The TypeScript 6 program that
 * reads calculate is built once: it loads the app's full types and takes a few seconds.
 */
import { beforeAll, describe, expect, test } from 'bun:test';
import { join } from 'node:path';
import {
  type App,
  allow,
  blend,
  defineApp,
  type Resource,
  type ResourceReview,
  reviewResource,
} from '@blendx/core';
import { parse } from 'yaml';
import { models as shop } from '../../dbml/test/golden/shop.schema.gen.ts';
import { type CalculateSource, extractCalculates } from '../src/calculates.ts';
import { emitReview } from '../src/emit-review.ts';
import { expectGolden } from './support/golden.ts';

const example = join(import.meta.dir, '..', '..', '..', 'examples', 'addition');
const blendFile = join(example, 'blends', 'addition_results.ts');

let review: ResourceReview;
let calculates: ReadonlyMap<string, CalculateSource> | undefined;
beforeAll(async () => {
  // Computed paths keep the example out of this package's tsc program.
  const resource = (await import(blendFile)).default as Resource;
  const app = (await import(join(example, 'src', 'app.ts'))).default as App;
  review = reviewResource(resource, app);
  calculates = extractCalculates([blendFile]).get(blendFile);
}, 60_000);

const additionReview = () =>
  emitReview({ review, calculates, source: 'blends/addition_results.ts' });

describe('emitReview', () => {
  test('the addition example', async () => {
    await expectGolden(join(example, 'review', 'addition_results.yaml'), additionReview());
  });

  test('the same review twice is the same text', () => {
    expect(additionReview()).toBe(additionReview());
  });

  test('stages shaped by a hook say so; calculate shows its source and writes', () => {
    const text = additionReview();
    expect(text).toContain("    calculate: the input's writable columns # from: schema, action\n");
    const store = parse(text).actions.store;
    expect(store.calculate).toEqual({
      source: '({ input }) => ({ result: input.a + input.b })',
      writes: ['result'],
    });
    expect(store.reply).toEqual({ status: 201, body: 'the record' });
  });

  test('a scoped index shows its scope, and its load says the action shaped it (D22)', () => {
    const orders = blend(shop.orders, {
      policy: allow.authenticated,
      actions: (a) => [
        a.index({ scope: ({ auth }) => ({ user_id: (auth as { id: number } | null)?.id }) }),
      ],
    });
    const scoped = reviewResource(orders, defineApp({}));
    const source = '({ auth }) => ({ user_id: auth?.id })';
    const text = emitReview({
      review: scoped,
      scopes: new Map([['index', { source, keys: ['user_id'] }]]),
      source: 'blends/orders.ts',
    });
    expect(text).toContain(
      'load: a filtered, sorted page of rows that are not soft-deleted # from: schema, action',
    );
    expect(parse(text).actions.index.scope).toEqual({ source, columns: ['user_id'] });
    const unread = emitReview({ review: scoped, source: 'blends/orders.ts' });
    expect(parse(unread).actions.index.scope).toBe(
      'not read: write scope inline in the blend file',
    );
  });

  test('an action that reveals hidden columns lists them, and its reply says so (D24)', () => {
    const users = blend(shop.users, {
      policy: allow.public,
      hidden: ['password'],
      actions: (a) => [a.store({ reveal: ['password'] }), a.show()],
    });
    const text = emitReview({
      review: reviewResource(users, defineApp({})),
      source: 'blends/users.ts',
    });
    expect(text).toContain('reveals: [password]');
    const { actions } = parse(text);
    expect(actions.store.reveals).toEqual(['password']);
    expect(actions.store.reply).toEqual({ status: 201, body: 'the record, with password' });
    expect(actions.show.reveals).toBeUndefined();
  });

  test('hidden columns, resource hooks, and a default calculate', () => {
    const users = blend(shop.users, {
      policy: allow.when(({ auth }) => auth !== null, { description: 'signed-in users' }),
      hidden: ['password'],
      hooks: { authorize: ({ prev }) => prev },
      actions: (a) => [a.store(), a.show()],
    });
    const text = emitReview({
      review: reviewResource(users, defineApp({})),
      source: 'blends/users.ts',
    });
    expect(text).toStartWith('# Generated by `blendx review`.');
    expect(text).toContain('\nhidden: [password]\n');
    expect(text).toContain('    authorize: signed-in users # from: schema, resource\n');
    const parsed = parse(text);
    expect(parsed.format).toBe(1);
    expect(parsed.record.password).toBeUndefined();
    expect(parsed.actions.store.calculate).toEqual({
      writes: ['display_name', 'email', 'is_active', 'password'],
    });
    expect(parsed.actions.show.calculate).toBeUndefined();
  });

  test('after is listed where a hook sets it, between save and respond (D26)', () => {
    const orders = blend(shop.orders, {
      policy: allow.public,
      actions: (a) => [a.show(), a.update({ after: () => {} })],
    });
    const text = emitReview({
      review: reviewResource(orders, defineApp({})),
      source: 'blends/orders.ts',
    });
    expect(text).toContain('    after: nothing # from: schema, action\n');
    const { actions } = parse(text);
    expect(Object.keys(actions.update.stages)).toEqual([
      ...['rules', 'load', 'authorize', 'calculate', 'save', 'after', 'respond'],
    ]);
    expect(actions.show.stages).not.toHaveProperty('after');
  });

  test("a resource's includes follow its record (D28)", () => {
    const users = blend(shop.users, {
      policy: allow.public,
      hidden: ['password'],
      actions: (a) => [a.show()],
    });
    const notes = blend(shop.order_notes, { policy: allow.public, actions: (a) => [a.show()] });
    const orders = blend(shop.orders, {
      policy: allow.public,
      includes: { user: users, notes: { blend: notes, limit: 3, sort: '-id' } },
      actions: (a) => [a.show()],
    });
    const parsed = parse(
      emitReview({ review: reviewResource(orders, defineApp({})), source: 'blends/orders.ts' }),
    );
    expect(Object.keys(parsed)).toEqual([
      ...['format', 'resource', 'source', 'record', 'includes', 'actions'],
    ]);
    expect(parsed.includes).toEqual({
      user: `users, through its show: ${users.policies.show?.description}`,
      notes: 'order_notes, at most 3, by id descending, through its show: public',
    });
  });

  test('later is listed where a hook sets it, between save and after (D27)', () => {
    const orders = blend(shop.orders, {
      policy: allow.public,
      actions: (a) => [a.update({ later: () => {}, after: () => {} })],
    });
    const text = emitReview({
      review: reviewResource(orders, defineApp({})),
      source: 'blends/orders.ts',
    });
    expect(text).toContain('    later: nothing # from: schema, action\n');
    expect(Object.keys(parse(text).actions.update.stages)).toEqual([
      ...['rules', 'load', 'authorize', 'calculate', 'save', 'later', 'after', 'respond'],
    ]);
  });
});
