// Generated by blendx from schema.dbml. Do not edit; run `blendx generate`.

import { doublePrecision, integer, pgTable, timestamp } from "drizzle-orm/pg-core";

export const addition_results = pgTable("addition_results", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  result: doublePrecision(),
  created_at: timestamp({ mode: "string" }),
  updated_at: timestamp({ mode: "string" }),
  deleted_at: timestamp({ mode: "string" }),
});

export const models = {
  addition_results: {
    name: "addition_results",
    table: addition_results,
    meta: {
      primaryKey: ["id"],
      timestamps: { createdAt: "created_at", updatedAt: "updated_at" },
      softDelete: "deleted_at",
      generated: ["id", "created_at", "updated_at", "deleted_at"],
      constraints: {
        "addition_results_pkey": { kind: "primaryKey", columns: ["id"] },
      },
    },
  },
} as const;
