// Generated by blendx from schema.dbml. Do not edit; run `blendx generate`.

import { bigint, boolean, date, foreignKey, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uuid, varchar } from "drizzle-orm/pg-core";

export const order_status = pgEnum("order_status", ["pending", "paid", "refunded"]);

export const users = pgTable("users", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  email: varchar({ length: 255 }).notNull().unique("users_email_key"),
  password: varchar({ length: 255 }).notNull(),
  display_name: varchar({ length: 80 }),
  is_active: boolean().notNull().default(true),
  created_at: timestamp({ mode: "string", withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp({ mode: "string", withTimezone: true }).notNull().defaultNow(),
});

export const orders = pgTable("orders", {
  id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
  user_id: integer().notNull(),
  status: order_status().notNull().default("pending"),
  total: numeric({ precision: 10, scale: 2 }).notNull(),
  quantity: integer().notNull().default(1),
  tags: text().array(),
  meta: jsonb(),
  public_id: uuid().notNull().unique("orders_public_id_key").defaultRandom(),
  placed_on: date({ mode: "string" }),
  created_at: timestamp({ mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp({ mode: "string" }).notNull().defaultNow(),
  deleted_at: timestamp({ mode: "string" }),
}, (t) => [
  foreignKey({ name: "orders_user_id_fkey", columns: [t.user_id], foreignColumns: [users.id] }),
  index("orders_user_status_idx").on(t.user_id, t.status),
  index("orders_created_at_idx").on(t.created_at),
]);

export const order_notes = pgTable("order_notes", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  order_id: bigint({ mode: "number" }).notNull(),
  body: text().notNull(),
  created_at: timestamp({ mode: "string" }).notNull().defaultNow(),
}, (t) => [
  foreignKey({ name: "order_notes_order_id_fkey", columns: [t.order_id], foreignColumns: [orders.id] }).onDelete("cascade"),
]);

export const models = {
  users: {
    name: "users",
    table: users,
    meta: {
      primaryKey: "id",
      timestamps: { createdAt: "created_at", updatedAt: "updated_at" },
      softDelete: null,
      generated: ["id", "created_at", "updated_at"],
    },
  },
  orders: {
    name: "orders",
    table: orders,
    meta: {
      primaryKey: "id",
      timestamps: { createdAt: "created_at", updatedAt: "updated_at" },
      softDelete: "deleted_at",
      generated: ["id", "created_at", "updated_at", "deleted_at"],
    },
  },
  order_notes: {
    name: "order_notes",
    table: order_notes,
    meta: {
      primaryKey: "id",
      timestamps: { createdAt: "created_at", updatedAt: null },
      softDelete: null,
      generated: ["id", "created_at"],
    },
  },
} as const;
