/**
 * Emits outbox.gen.ts (D27). Once any app, resource or action later hook exists, it re-exports
 * core's blendx_outbox table; drizzle.config.gen.ts lists the file, so `blendx migrate
 * generate` creates the table in the app's own migrations. Without later hooks it exports
 * nothing, and the app has no outbox table.
 */
const HEADER =
  '// Generated by blendx from blends/ and src/app.ts. Do not edit; run `blendx generate`.';

export function emitOutbox(hasLater: boolean): string {
  const body = hasLater
    ? '// The table later hooks write their entries to (D27).\n\nexport { outbox } from "blendx/drizzle";'
    : '// No hook of this app is a later hook, so it has no outbox table (D27).\n\nexport {};';
  return `${HEADER}\n${body}\n`;
}
