/**
 * Emits routes.gen.ts: one chained Hono route per endpoint, each handed to the generic run()
 * controller. Resources sort by table and endpoints keep the toEndpoints() order, so
 * /orders/quote is registered before /orders/:id. The file exports AppType for hc.
 */
import { type Resource, toEndpoints } from '@blendx/core';

const HEADER = '// Generated by blendx from blends/. Do not edit; run `blendx generate`.';

export interface BlendModule {
  /** Import specifier of the blend file, relative to routes.gen.ts: '../../blends/orders.ts'. */
  specifier: string;
  /** The blend file's default export. */
  resource: Resource;
}

/** Names a table can't be bound to as-is: JS reserved words and the file's own imports. */
const RESERVED = new Set([
  ...['await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default'],
  ...['delete', 'do', 'else', 'enum', 'export', 'extends', 'false', 'finally', 'for'],
  ...['function', 'if', 'implements', 'import', 'in', 'instanceof', 'interface', 'let', 'new'],
  ...['null', 'package', 'private', 'protected', 'public', 'return', 'static', 'super'],
  ...['switch', 'this', 'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with'],
  ...['yield', 'router', 'run'],
]);

const str = (value: string) => JSON.stringify(value);
const byCodeUnit = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

/** Emits routes.gen.ts for the app's blends. Output is deterministic. */
export function emitRoutes(blends: readonly BlendModule[]): string {
  const sorted = [...blends].sort((a, b) =>
    byCodeUnit(a.resource.model.name, b.resource.model.name),
  );

  const owners = new Map<string, string>();
  const routes = new Map<string, string>();
  const imports: string[] = [];
  const chain: string[] = [];
  for (const { specifier, resource } of sorted) {
    const table = resource.model.name;
    const owner = owners.get(table);
    if (owner) throw new Error(`${owner} and ${specifier} both blend ${table}`);
    owners.set(table, specifier);

    const binding = RESERVED.has(table) ? `${table}_` : table;
    imports.push(`import ${binding} from ${str(specifier)};`);
    for (const endpoint of toEndpoints(resource)) {
      const route = `${endpoint.method.toUpperCase()} ${endpoint.path}`;
      const taken = routes.get(route);
      if (taken) throw new Error(`${taken} and ${endpoint.id} both route ${route}`);
      routes.set(route, endpoint.id);
      chain.push(
        `  .${endpoint.method}(${str(endpoint.path)}, ...run(${binding}, ${str(endpoint.action)}))`,
      );
    }
  }

  const importLines = ['import { router, run } from "blendx";', ...imports].join('\n');
  const routesLine = `export const routes = router()${chain.map((line) => `\n${line}`).join('')};`;
  return `${[HEADER, importLines, routesLine, 'export type AppType = typeof routes;'].join('\n\n')}\n`;
}
