/**
 * Renders the review model as review/<resource>.yaml (P10.3) for a human to read. The yaml
 * Document API carries the comments: a header, and `# from:` on every stage that more than
 * the schema shaped. Deterministic: no timestamps, no line folding.
 */
import type { ActionReview, AppReview, ResourceReview } from '@blendx/core';
import { Document, isMap, isScalar, isSeq, type YAMLMap } from 'yaml';
import type { CalculateSource, HookSource } from './calculates.ts';

const HEADER = [
  ' Generated by `blendx review`. Do not edit: a change here is a fix request.',
  ' Change the blend until `blendx review --check` passes.',
].join('\n');

/** In pipeline order; later and after (D26, D27) appear only on actions whose review lists them. */
const STAGES = [
  'rules',
  'load',
  'authorize',
  'calculate',
  'save',
  'later',
  'after',
  'respond',
] as const;
const BUILTINS: ReadonlySet<string> = new Set([
  'index',
  'show',
  'store',
  'update',
  'replace',
  'destroy',
  'restore',
  'purge',
]);

/** Blocks that hold a hook's source, and the lists printed on one line beside it. */
const SOURCE_BLOCKS = [
  ['scope', ['columns']],
  ['calculate', ['writes', 'returns']],
] as const;

type CustomStage = 'authorize' | 'save';

const limitations: Record<CustomStage, string> = {
  authorize: 'Custom hooks can change this policy decision.',
  save: 'A custom save hook controls persistence and may not call this default.',
};
const declaredWriteLimitation = 'Declared related-table writes occur outside this default.';

const TAB_WIDTH = 2;

/** Expands tabs used for indentation without changing source text after the first token. */
function expandIndentation(line: string): string {
  let column = 0;
  let index = 0;
  let indentation = '';
  while (index < line.length) {
    const character = line[index];
    if (character === ' ') {
      indentation += character;
      column += 1;
      index += 1;
      continue;
    }
    if (character === '\t') {
      const width = TAB_WIDTH - (column % TAB_WIDTH);
      indentation += ' '.repeat(width);
      column += width;
      index += 1;
      continue;
    }
    break;
  }
  return indentation + line.slice(index);
}

const indentOf = (line: string) => line.length - line.trimStart().length;

/** Normalizes line endings and indentation for a literal YAML source block. */
function dedent(source: string): string {
  const [first = '', ...rest] = source
    .replaceAll('\r\n', '\n')
    .replaceAll('\r', '\n')
    .split('\n')
    .map(expandIndentation);
  const indents = rest.filter((line) => line.trim() !== '').map(indentOf);
  const cut = indents.length > 0 ? Math.min(...indents) : 0;
  return [first, ...rest.map((line) => line.slice(Math.min(cut, indentOf(line))))].join('\n');
}

/** calculate as the reviewer reads it: the hook and its keys, or the default's keys. */
function calculateOf(action: ActionReview, found: CalculateSource | undefined): unknown {
  // A member route carries a key segment, `:id` or one per column of a composite key (D33).
  const collection = !BUILTINS.has(action.name) && !action.route.includes('/:');
  const label = collection ? 'returns' : 'writes';
  if (found) return { source: found.source, [label]: found.keys };
  if (action.calculate) return { [label]: [...action.calculate.keys] };
  if (action.stages.calculate.from.includes('action')) {
    return 'not read: write calculate inline in the blend file';
  }
  return undefined;
}

/** An index's scope as the reviewer reads it: the function and its columns (D22). */
function scopeOf(action: ActionReview, found: CalculateSource | undefined): unknown {
  if (found) return { source: found.source, columns: found.keys };
  if (action.scoped) return 'not read: write scope inline in the blend file';
  return undefined;
}

export interface ReviewInput {
  review: ResourceReview;
  /** calculate hooks by action name, from extractCalculates() or extractHooks(). */
  calculates?: ReadonlyMap<string, CalculateSource>;
  /** scope functions by action name, from extractHooks(). */
  scopes?: ReadonlyMap<string, CalculateSource>;
  /** The blend file, relative to the app root. */
  source: string;
  /** The app module, relative to the app root, when app hooks appear in the review. */
  appSource?: string;
  /** Direct inline custom authorize/save hooks, grouped by their cascade level. */
  stageHooks?: {
    app?: ReadonlyMap<string, HookSource>;
    resource?: ReadonlyMap<string, HookSource>;
    action?: ReadonlyMap<string, ReadonlyMap<string, HookSource>>;
  };
}

/** A custom authorize or save hook needs more than the schema default describes (P17.2). */
function customStage(
  action: ActionReview,
  stage: CustomStage,
  source: string,
  appSource: string | undefined,
  stageHooks: ReviewInput['stageHooks'],
): unknown {
  const review = action.stages[stage];
  const levels = review.from.filter((level) => level !== 'schema');
  const writes = stage === 'save' ? action.writes : undefined;
  const membership = stage === 'authorize' ? review.membership : undefined;
  const structured = levels.length > 0 || Boolean(writes?.length);
  if (!structured && !membership) return review.default;
  const hookSource = (level: string) => {
    if (level === 'app') return stageHooks?.app?.get(stage)?.source;
    if (level === 'resource') return stageHooks?.resource?.get(stage)?.source;
    return stageHooks?.action?.get(action.name)?.get(stage)?.source;
  };
  return {
    default: review.default,
    ...(membership ? { membership } : {}),
    ...(structured
      ? { limitation: levels.length > 0 ? limitations[stage] : declaredWriteLimitation }
      : {}),
    ...(levels.length > 0
      ? {
          hooks: Object.fromEntries(
            levels.map((level) => [
              level,
              {
                file: level === 'app' ? (appSource ?? 'app source unavailable') : source,
                source:
                  hookSource(level) ?? `not read: write the ${stage} hook inline in this file`,
              },
            ]),
          ),
        }
      : {}),
    ...(writes?.length ? { writes } : {}),
  };
}

/** The text of review/<resource>.yaml. */
export function emitReview({
  review,
  calculates = new Map(),
  scopes = new Map(),
  source,
  appSource,
  stageHooks,
}: ReviewInput): string {
  const actions = review.actions.map((action) => {
    const scope = scopeOf(action, scopes.get(action.name));
    const calculate = calculateOf(action, calculates.get(action.name));
    return [
      action.name,
      {
        route: action.route,
        ...(Object.keys(action.input).length > 0 ? { input: action.input } : {}),
        stages: Object.fromEntries(
          STAGES.flatMap((stage) => {
            const listed = action.stages[stage];
            return listed
              ? [
                  [
                    stage,
                    stage === 'authorize' || stage === 'save'
                      ? customStage(action, stage, source, appSource, stageHooks)
                      : listed.default,
                  ],
                ]
              : [];
          }),
        ),
        ...(scope === undefined ? {} : { scope }),
        ...(calculate === undefined ? {} : { calculate }),
        ...(action.resets
          ? {
              resets: {
                to_default: [...action.resets.to_default],
                to_null: [...action.resets.to_null],
              },
            }
          : {}),
        ...(action.reveals ? { reveals: [...action.reveals] } : {}),
        reply: action.reply,
      },
    ] as const;
  });

  const doc = new Document({
    format: review.format,
    resource: review.resource,
    source,
    ...(review.hidden.length > 0 ? { hidden: [...review.hidden] } : {}),
    record: review.record,
    ...(review.includes ? { includes: review.includes } : {}),
    actions: Object.fromEntries(actions),
  });
  doc.commentBefore = HEADER;

  const hidden = doc.get('hidden');
  if (isSeq(hidden)) hidden.flow = true;

  const items = (doc.get('actions') as YAMLMap).items;
  for (const [index, pair] of items.entries()) {
    const action = review.actions[index];
    if (!action || !isMap(pair.value)) continue;
    if (index > 0 && isScalar(pair.key)) pair.key.spaceBefore = true;

    const stages = pair.value.get('stages');
    for (const stage of STAGES) {
      const from = action.stages[stage]?.from ?? [];
      const node = isMap(stages) ? stages.get(stage, true) : undefined;
      if (from.length > 1 && isScalar(node)) node.comment = ` from: ${from.join(', ')}`;
    }

    for (const [block, lists] of SOURCE_BLOCKS) {
      const found = pair.value.get(block);
      if (!isMap(found)) continue;
      const hook = found.get('source', true);
      if (isScalar(hook)) {
        hook.value = dedent(String(hook.value));
        hook.type = 'BLOCK_LITERAL';
      }
      for (const key of lists) {
        const keys = found.get(key);
        if (isSeq(keys)) keys.flow = true;
      }
    }

    const stageMap = pair.value.get('stages');
    if (isMap(stageMap)) {
      for (const stage of ['authorize', 'save'] as const) {
        const custom = stageMap.get(stage, true);
        if (!isMap(custom)) continue;
        const hooks = custom.get('hooks', true);
        if (isMap(hooks)) {
          for (const item of hooks.items) {
            if (!isMap(item.value)) continue;
            const hook = item.value.get('source', true);
            if (!isScalar(hook) || String(hook.value).startsWith('not read:')) continue;
            hook.value = dedent(String(hook.value));
            hook.type = 'BLOCK_LITERAL';
          }
        }
        const writes = custom.get('writes', true);
        if (isSeq(writes)) writes.flow = true;
        const membership = custom.get('membership', true);
        if (isMap(membership)) {
          const via = membership.get('via', true);
          if (isSeq(via)) via.flow = true;
          const related = membership.get('related', true);
          if (isMap(related)) {
            for (const item of related.items) {
              if (!isMap(item.value)) continue;
              const relatedVia = item.value.get('via', true);
              if (isSeq(relatedVia)) relatedVia.flow = true;
            }
          }
        }
      }
    }

    const reveals = pair.value.get('reveals');
    if (isSeq(reveals)) reveals.flow = true;

    // D34: what a replace resets, one line per kind.
    const resets = pair.value.get('resets');
    if (isMap(resets)) {
      for (const item of resets.items) if (isSeq(item.value)) item.value.flow = true;
    }
  }

  return doc.toString({ lineWidth: 0, flowCollectionPadding: false });
}

/** The text of review/app-actions.yaml for typed domain actions (D37). */
export function emitAppReview({ review, source }: { review: AppReview; source: string }): string {
  const doc = new Document({
    format: review.format,
    app_actions: true,
    source,
    actions: Object.fromEntries(
      review.actions.map((action) => [
        action.name,
        {
          route: action.route,
          policy: action.policy,
          ...(action.input_format
            ? { input_format: action.input_format, max_bytes: action.max_bytes }
            : {}),
          ...(Object.keys(action.input).length > 0 ? { input: action.input } : {}),
          writes: [...action.writes],
          reply: action.reply,
          errors: [...action.errors],
        },
      ]),
    ),
  });
  doc.commentBefore = HEADER;

  const actions = doc.get('actions');
  if (isMap(actions)) {
    for (const [index, pair] of actions.items.entries()) {
      if (!isMap(pair.value)) continue;
      if (index > 0 && isScalar(pair.key)) pair.key.spaceBefore = true;
      for (const key of ['writes', 'errors']) {
        const list = pair.value.get(key, true);
        if (isSeq(list)) list.flow = true;
      }
    }
  }
  return doc.toString({ lineWidth: 0, flowCollectionPadding: false });
}
