/**
 * Emits register.gen.ts. It registers the app with blendx, so every policy and hook sees
 * the identity type the app's auth function returns (docs/decisions.md D9).
 */
const HEADER = '// Generated by blendx from the app module. Do not edit; run `blendx generate`.';

/** `appSpecifier`: the module that default-exports defineApp(), relative to register.gen.ts. */
export function emitRegister(appSpecifier: string): string {
  return `${HEADER}

import type app from ${JSON.stringify(appSpecifier)};

declare module "blendx" {
  interface Register {
    app: typeof app;
  }
}
`;
}
