/**
 * Emits drizzle.config.gen.ts for `blendx migrate generate`, which runs drizzle-kit from the
 * app root, so both paths are relative to that root. There are no credentials: generating
 * a migration is offline, and `blendx migrate up` uses blendx's own migrator.
 */
const HEADER = '// Generated by blendx from blendx.config.ts. Do not edit; run `blendx generate`.';

export interface DrizzleConfigPaths {
  /** schema.gen.ts, relative to the app root: './src/generated/schema.gen.ts'. */
  schema: string;
  /** The migrations folder, relative to the app root: './drizzle'. */
  out: string;
}

export function emitDrizzleConfig(paths: DrizzleConfigPaths): string {
  return `${HEADER}

export default {
  dialect: "postgresql",
  schema: ${JSON.stringify(paths.schema)},
  out: ${JSON.stringify(paths.out)},
};
`;
}
