/**
 * Emits drizzle.config.gen.ts for `blendx migrate generate`, which runs drizzle-kit from the
 * app root, so both paths are relative to that root. There are no credentials: generating
 * a migration is offline, and `blendx migrate up` uses blendx's own migrator.
 */
const HEADER = '// Generated by blendx from blendx.config.ts. Do not edit; run `blendx generate`.';

export interface DrizzleConfigPaths {
  /** schema.gen.ts and outbox.gen.ts (D27), relative to the app root. */
  schema: readonly string[];
  /** The migrations folder, relative to the app root: './drizzle'. */
  out: string;
}

export function emitDrizzleConfig(paths: DrizzleConfigPaths): string {
  const schema = paths.schema.map((path) => `    ${JSON.stringify(path)},`).join('\n');
  return `${HEADER}

export default {
  dialect: "postgresql",
  schema: [
${schema}
  ],
  out: ${JSON.stringify(paths.out)},
};
`;
}
