/**
 * Renders the review model as review/<resource>.yaml (P10.3) for a human to read. The yaml
 * Document API carries the comments: a header, and `# from:` on every stage that more than
 * the schema shaped. Deterministic: no timestamps, no line folding.
 */
import type { ActionReview, ResourceReview } from '@blendx/core';
import { Document, isMap, isScalar, isSeq, type YAMLMap } from 'yaml';
import type { CalculateSource } from './calculates.ts';

const HEADER = [
  ' Generated by `blendx review`. Do not edit: a change here is a fix request.',
  ' Change the blend until `blendx review --check` passes.',
].join('\n');

const STAGES = ['rules', 'load', 'authorize', 'calculate', 'save', 'respond'] as const;
const BUILTINS: ReadonlySet<string> = new Set([
  'index',
  'show',
  'store',
  'update',
  'destroy',
  'restore',
]);

const indentOf = (line: string) => line.length - line.trimStart().length;

/** Removes the indentation the hook had in the blend file from its later lines. */
function dedent(source: string): string {
  const [first = '', ...rest] = source.split('\n');
  const indents = rest.filter((line) => line.trim() !== '').map(indentOf);
  const cut = indents.length > 0 ? Math.min(...indents) : 0;
  return [first, ...rest.map((line) => line.slice(Math.min(cut, indentOf(line))))].join('\n');
}

/** calculate as the reviewer reads it: the hook and its keys, or the default's keys. */
function calculateOf(action: ActionReview, found: CalculateSource | undefined): unknown {
  const collection = !BUILTINS.has(action.name) && !action.route.includes('/:id');
  const label = collection ? 'returns' : 'writes';
  if (found) return { source: found.source, [label]: found.keys };
  if (action.calculate) return { [label]: [...action.calculate.keys] };
  if (action.stages.calculate.from.includes('action')) {
    return 'not read: write calculate inline in the blend file';
  }
  return undefined;
}

export interface ReviewInput {
  review: ResourceReview;
  /** calculate hooks by action name, from extractCalculates(). */
  calculates?: ReadonlyMap<string, CalculateSource>;
  /** The blend file, relative to the app root. */
  source: string;
}

/** The text of review/<resource>.yaml. */
export function emitReview({ review, calculates = new Map(), source }: ReviewInput): string {
  const actions = review.actions.map((action) => {
    const calculate = calculateOf(action, calculates.get(action.name));
    return [
      action.name,
      {
        route: action.route,
        ...(Object.keys(action.input).length > 0 ? { input: action.input } : {}),
        stages: Object.fromEntries(STAGES.map((stage) => [stage, action.stages[stage].default])),
        ...(calculate === undefined ? {} : { calculate }),
        reply: action.reply,
      },
    ] as const;
  });

  const doc = new Document({
    format: review.format,
    resource: review.resource,
    source,
    ...(review.hidden.length > 0 ? { hidden: [...review.hidden] } : {}),
    record: review.record,
    actions: Object.fromEntries(actions),
  });
  doc.commentBefore = HEADER;

  const hidden = doc.get('hidden');
  if (isSeq(hidden)) hidden.flow = true;

  const items = (doc.get('actions') as YAMLMap).items;
  for (const [index, pair] of items.entries()) {
    const action = review.actions[index];
    if (!action || !isMap(pair.value)) continue;
    if (index > 0 && isScalar(pair.key)) pair.key.spaceBefore = true;

    const stages = pair.value.get('stages');
    for (const stage of STAGES) {
      const from = action.stages[stage].from;
      const node = isMap(stages) ? stages.get(stage, true) : undefined;
      if (from.length > 1 && isScalar(node)) node.comment = ` from: ${from.join(', ')}`;
    }

    const calculate = pair.value.get('calculate');
    if (isMap(calculate)) {
      const hook = calculate.get('source', true);
      if (isScalar(hook)) {
        hook.value = dedent(String(hook.value));
        hook.type = 'BLOCK_LITERAL';
      }
      for (const key of ['writes', 'returns']) {
        const keys = calculate.get(key);
        if (isSeq(keys)) keys.flow = true;
      }
    }
  }

  return doc.toString({ lineWidth: 0, flowCollectionPadding: false });
}
